title: "ゲームグラフィックス特論"
summary: "3次元コンピュータグラフィックスの理論と実装方法のうち, 特に3Dゲームなどのインタラクティブなアプリケーションを実現する上で必要になるリアルタイムレンダリングの技術の学習を通して, 現在のCGシステムで用いられている各種の技術や考え方を理解し, それを応用したシステムを実装するための知識とノウハウを習得します. 学部科目の「コンピュータグラフィックス」に続く進歩的な内容であり, 教科書的な内容にとどまらず, 現実のシステムで応用されている技術の具体的な内容の一端に触れることを目指します."
topics: [ "3DCG", "RealtimeRendering", "ProgrammableShader", "OpenGL", "GLSL" ]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - pipeline
  - development
  